"""Checkpoint cost model for profile-driven adaptive checkpoint decisions.

Loads a checkpoint_cost_profile.json (generated by profile_checkpoint_costs.py)
and provides cost functions for replay, load, and checkpoint operations.

Usage:
    model = CheckpointCostModel("experiments/checkpoint_cost_profile.json")
    should_publish = model.should_publish(L, u, S, delta_S, lambda_=1.0)
"""

import json
from pathlib import Path


class CheckpointCostModel:
    """Piecewise linear cost model for checkpoint operations.

    Loads a profile JSON with measurements of:
    - T_prefill(n): latency to prefill n tokens
    - T_load(S): latency to restore S bytes of KV cache
    - T_ckpt(S): latency to save S bytes of KV cache
    - c0: fixed publication overhead (independent of size)

    All are evaluated via linear interpolation with clamping at boundaries.
    """

    def __init__(self, profile_path: str):
        """Load profile JSON and validate.

        Args:
            profile_path: Path to checkpoint_cost_profile.json

        Raises:
            ValueError: If profile contains placeholder data (is_real_measurement=False)
            FileNotFoundError: If profile file does not exist
            json.JSONDecodeError: If profile JSON is invalid
        """
        with open(profile_path) as f:
            profile = json.load(f)

        # Reject placeholder profiles — must be from real measurements
        if not profile.get("meta", {}).get("is_real_measurement", False):
            notes = profile.get("meta", {}).get("notes", "")
            raise ValueError(
                f"Profile {profile_path} contains placeholder data: {notes}. "
                "Run profile_checkpoint_costs.py on real hardware first."
            )

        self._c0 = profile["publication_overhead_ms"]

        # Parse and sort data points for linear interpolation
        self._prefill = sorted((int(k), v) for k, v in profile["prefill_ms_by_tokens"].items())
        self._load = sorted((int(k), v) for k, v in profile["load_ms_by_bytes"].items())
        self._ckpt = sorted((int(k), v) for k, v in profile["checkpoint_ms_by_bytes"].items())

    @staticmethod
    def _interp(x: int, table: list[tuple[int, float]]) -> float:
        """Piecewise linear interpolation with clamping.

        Args:
            x: Query point
            table: Sorted list of (key, value) measurement points

        Returns:
            Interpolated value, clamped to table boundaries
        """
        if not table:
            return 0.0

        if x <= table[0][0]:
            return table[0][1]
        if x >= table[-1][0]:
            return table[-1][1]

        # Find surrounding points
        for i in range(len(table) - 1):
            x1, y1 = table[i]
            x2, y2 = table[i + 1]
            if x1 <= x <= x2:
                # Linear interpolation
                t = (x - x1) / (x2 - x1) if x2 != x1 else 0
                return y1 + t * (y2 - y1)

        return table[-1][1]

    def t_prefill(self, n_tokens: int) -> float:
        """Evaluate T_prefill(n) for n tokens."""
        return self._interp(n_tokens, self._prefill)

    def t_load(self, n_bytes: int) -> float:
        """Evaluate T_load(S) for S bytes of KV cache."""
        return self._interp(n_bytes, self._load)

    def t_ckpt(self, n_bytes: int) -> float:
        """Evaluate T_ckpt(S) for S bytes of KV cache."""
        return self._interp(n_bytes, self._ckpt)

    def should_publish(
        self,
        published_tokens: int,  # L
        unpublished_tokens: int,  # u
        published_bytes: int,  # S
        delta_bytes: int,  # ΔS
        lambda_: float = 1.0,
    ) -> bool:
        """Decide whether to publish a checkpoint.

        Rule: Publish if T_replay(L, u) > T_load(ΔS) + λ * T_ckpt(ΔS) + c0

        Args:
            published_tokens: L — previously published stable tokens
            unpublished_tokens: u — unpublished tokens since last checkpoint
            published_bytes: S — KV cache bytes in published checkpoint
            delta_bytes: ΔS — incremental KV bytes to checkpoint
            lambda_: λ — weight on checkpoint cost (default 1.0)

        Returns:
            True if checkpoint should be published, False otherwise
        """
        replay_cost = self.t_prefill(published_tokens + unpublished_tokens) - self.t_prefill(
            published_tokens
        )
        load_cost = self.t_load(published_bytes + delta_bytes) - self.t_load(published_bytes)
        ckpt_cost = self.t_ckpt(delta_bytes)

        total_cost = load_cost + lambda_ * ckpt_cost + self._c0

        return replay_cost > total_cost
